#!/bin/bash

## forces traffic via a separate docker instance which will add the bearer token to the
## requests made by ffmpeg

dig +short host.docker.internal > /tmp/host-ip
iptables -t nat -A OUTPUT -p tcp --dport 443 -j DNAT --to-destination `cat /tmp/host-ip`:5050

exec ffmpeg "$@"
